### ISSUE TITLE
Update the code to support aioredis `v2.0.0` API

### ISSUE THREAD

**Issue by clintonroy** [bluesky/bluesky-queueserver#185]
Hellos,
I've had to restrict the version of aioredis to 1.3.1, seemingly 2.x has a breaking API, I have not looked too deeply into this at all.

```
bluesky-queueserver_1       | INFO:bluesky_queueserver.manager.manager:Starting ZMQ server at 'tcp://*:60615'
bluesky-queueserver_1       | INFO:bluesky_queueserver.manager.manager:ZMQ control channels: encryption disabled
bluesky-queueserver_1       | INFO:bluesky_queueserver.manager.manager:Starting RE Manager process
bluesky-queueserver_1       | ERROR:bluesky_queueserver.manager.manager:Exiting RE Manager with exception module 'aioredis' has no attribute 'create_redis_pool'
bluesky-queueserver_1       | Traceback (most recent call last):
bluesky-queueserver_1       |   File "/home/asuser/.venv/lib/python3.9/site-packages/bluesky_queueserver/manager/manager.py", line 1929, in run
bluesky-queueserver_1       |     asyncio.run(self.zmq_server_comm())
bluesky-queueserver_1       |   File "/usr/lib64/python3.9/asyncio/runners.py", line 44, in run
bluesky-queueserver_1       |     return loop.run_until_complete(main)
bluesky-queueserver_1       |   File "/usr/lib64/python3.9/asyncio/base_events.py", line 642, in run_until_complete
bluesky-queueserver_1       |     return future.result()
bluesky-queueserver_1       |   File "/home/asuser/.venv/lib/python3.9/site-packages/bluesky_queueserver/manager/manager.py", line 1810, in zmq_server_comm
bluesky-queueserver_1       |     await self._plan_queue.start()
bluesky-queueserver_1       |   File "/home/asuser/.venv/lib/python3.9/site-packages/bluesky_queueserver/manager/plan_queue_ops.py", line 224, in start
bluesky-queueserver_1       |     self._r_pool = await aioredis.create_redis_pool(f"redis://{self._redis_host}", encoding="utf8")
bluesky-queueserver_1       | AttributeError: module 'aioredis' has no attribute 'create_redis_pool'
bluesky-queueserver_1       | ERROR:bluesky_queueserver.manager.start_manager:Timeout detected by Watchdog. RE Manager malfunctioned and must be restarted
```

**Comment by dmgav** [comment]
Thanks. The version of `aioredis` will be pinned to v1.3.1 in next PR https://github.com/bluesky/bluesky-queueserver/pull/184. We will address the issue later.

**Comment by dmgav** [comment]
Resolved in PR https://github.com/bluesky/bluesky-queueserver/pull/206
